services:
  traefik:
    image: traefik:v3.1
    container_name: traefik
    command:
      - "--api.dashboard=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8081:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - uhm-network

  # Zookeeper and Kafka Services
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - uhm-network

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper
    networks:
      - uhm-network
  
  # Eureka Service
  eureka-service:
    build:
      context: ./eureka-service
      dockerfile: deployment/Dockerfile
    container_name: eureka-service
    networks:
      - uhm-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.eureka.rule=Host(`eureka-service`)"
      - "traefik.http.services.eureka.loadbalancer.server.port=8761"

  # Elastic Search Database
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.18.1
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - "ES_DEFAULT_SHARDS=1"
      - "ES_DEFAULT_REPLICAS=0"
    ports:
      - "9200:9200"
    volumes:
      - elastic_data:/usr/share/elasticsearch/data
    networks:
      - uhm-network
  # Kibana for Elastic Search
  kibana:
    image: docker.elastic.co/kibana/kibana:8.18.1
    container_name: kibana
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - uhm-network

  # Audit Service
  audit-service:
    build:
      context: ./audit-service
      dockerfile: deployment/Dockerfile
    container_name: audit-service
    environment:
      AUDIT_BOOTSTRAP_SERVERS: ${AUDIT_BOOTSTRAP_SERVERS}
      AUDIT_GROUP_ID: ${AUDIT_GROUP_ID}
      AUDIT_DB_HOST: ${AUDIT_DB_HOST}
      AUDIT_TOPIC: ${AUDIT_TOPIC}
      EUREKA_URL: ${EUREKA_URL}
    env_file: .env
    depends_on:
      - kafka
      - elasticsearch
    networks:
      - uhm-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.audit.rule=Host(`audit-service`)"
      - "traefik.http.services.audit.loadbalancer.server.port=8090"

  

networks:
  uhm-network:
    driver: bridge

volumes:
  elastic_data: