name: Java Quality Checks

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  check-format:
    name: Check Code Format
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Set up Gradle
        uses: gradle/gradle-build-action@v2

      - name: Run Spotless Check
        if: ${{ hashFiles('**/*.java') != '' }}
        run: gradle spotlessCheck --no-daemon

  lint:
    name: Java Lint Analysis
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Set up Gradle
        uses: gradle/gradle-build-action@v2

      - name: Run Checkstyle
        if: ${{ hashFiles('**/*.java') != '' }}
        run: gradle checkstyleMain --no-daemon